version: "2"
services:
  # SQS
  queue:
    image: softwaremill/elasticmq:latest
    ports:
      - 9324:9324      
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  # POSTGRESQL
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  # REDIS
  redis:
    image: redis
    ports:
      - "6379:6379"